#Line是重置成功后的提示 最多支持2行提示 Line1是第一行 Line2是第二行
#QQ是玩家在QQ内发送 重置密码XXXX 之后的消息
#密码随机位数为8 重置密码代码位数为4 无法修改
Line1: "§b§l系统已经将您的密码重置为:"
Line1_2: "使用/cp"
Line1_3: "新密码 即可更换默认密码"
Line2: "§e§l更换密码请重新进入服务器 登录密码使用§c§l随机密码 §e§l请你不要忘记"
QQ: "成功重置密码 随机密码将在游戏内显示 请使用/cp 随机密码 新密码 修改密码"
#Line3是忘记密码提示第一行
#Line4是忘记密码提示第二行
#Line5是忘记密码提示第三行
Line3: "§b§l忘记密码了吗 用你登录游戏的QQ号"
Line4: "§b§l在本服务器Q群发送:§r§e§l"
Line5: "§b§l即可重置您的密码!"