package org.ezapi.html;

import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;

import java.util.ArrayList;
import java.util.List;

public class HtmlContainer implements HtmlComponent, PageComponent {

    private final String language;

    private final List<HtmlContent> htmlContents = new ArrayList<>();

    public HtmlContainer(String language) {
        this.language = language;
        this.add(new Annotation("Generated by EasyAPI - HTML"));
    }

    public HtmlContainer add(HtmlContent htmlContent) {
        if (!htmlContents.contains(htmlContent)) {
            htmlContents.add(htmlContent);
        }
        return this;
    }

    public String parseToString() {
        StringBuilder in = new StringBuilder();
        for (HtmlContent htmlContent : htmlContents) {
            in.append(htmlContent.parseToString()).append("\n");
        }
        return "<!DOCTYPE html><html lang=\"" + this.language + "\">\n" + in + "</html>";
    }

    @Override
    public byte[] get() {
        return parseToString().getBytes();
    }

}
